var a = 10/0;
console.log(a);
console.log(typeof a);

var b = "Hello Sai";
console.log(b);
console.log(typeof b);

var c = false;
console.log(typeof c);


var d;
console.log(typeof d);
// console.log(x);

var e;
console.log(typeof e);
console.log(e);

var t= null;
console.log(typeof t);
console.log(t);
//complex Function
function greet(){
console.log("SAIII")
}
greet();
//Array
let numbers = [1,2,3,4,5,67,89,0];
console.log(numbers);
console.log(numbers[6]);//to print the value on index 6
console.log(numbers.indexOf(67));//to find index value
//object

let student= {
    id: 100,
    Name: "Saikiran",
    roll_no: 17,
    age:22
}
console.log(student);