function add() {
    let a = 10;
    let b = 40;
    let d = a+b;
    console.log(d);
}
add();

function square() {
            var num = 5;
            var res = num*num;
            console.log(res);
        }
square();

var square = (num) =>  num * num ;
console.log(square(4));
console.log(square(10));
console.log(square(5));

const greet = (name) => console.log("Good Evening " + name);
greet("Gamana");

var add = (a, b) => {
    let c = a + b;
    console.log(c);
}
add(10 , 10);

var a;
console.log(a);
var a = 10;
console.log(a);
a = "Sai";
console.log(a);
var a = true;
console.log(a);